version: '3.5'

services:
  sergent:
    image: manaty/sergent
    container_name: sergent
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /home/env-directory:/home/env-directory
    environment:
      SERGENT_COMMAND_PATH : /home/commands
